language: node_js
node_js:
  - "stable"
dist: bionic
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- npm run build
- cp dist/ngx-domoboard/index.html dist/ngx-domoboard/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngx-domoboard
  keep_history: true
  on:
    branch: master
